services:
  - type: web
    name: ck2-app
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    # Bind to Render's port:
    startCommand: npx next start -p $PORT
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.14.0
