services:
  - type: web
    name: ck2-app
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /
    envVars: []
